### ISSUE TITLE
wit_file_utils??

### ISSUE THREAD

**Issue by yassinerebas** [marouane53/transcribe#1]
[youtube] kdvc9Orfk-E: Downloading webpage
[youtube] kdvc9Orfk-E: Downloading ios player API JSON
[youtube] kdvc9Orfk-E: Downloading android player API JSON
[youtube] kdvc9Orfk-E: Downloading m3u8 information
[info] kdvc9Orfk-E: Downloading 1 format(s): 251
[download] Destination: E:\transcribe-main\downloads\kdvc9Orfk-E.webm
[download] 100% of   14.39MiB in 00:00:05 at 2.47MiB/s
[ExtractAudio] Destination: E:\transcribe-main\downloads\kdvc9Orfk-E.wav
Deleting original file E:\transcribe-main\downloads\kdvc9Orfk-E.webm (pass -k to keep)
Transcribing file: E:\transcribe-main\downloads\0URr_XkgAIE.wav
Local files:   0%|                                                                               | 0/1 [00:00<?, ?it/s]
URLs or local paths:   0%|                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\transcribe-main\transcribe.py", line 126, in <module>
    main()
  File "E:\transcribe-main\transcribe.py", line 95, in main
    transcribe_file(audio_file, language_sign)
  File "E:\transcribe-main\transcribe.py", line 85, in transcribe_file
    progress = deque(farrigh(config), maxlen=0)
  File "C:\Users\Ingecys\AppData\Local\Programs\Python\Python310\lib\site-packages\tafrigh\cli.py", line 94, in farrigh
    for progress_info, local_elements_segments in process_local(file_or_folder, model, config, progress_info):
  File "C:\Users\Ingecys\AppData\Local\Programs\Python\Python310\lib\site-packages\tafrigh\cli.py", line 151, in process_local
    wav_file_path = str(wit_file_utils.convert_to_wav(file['file_path']).absolute())
NameError: name 'wit_file_utils' is not defined. Did you mean: 'file_utils'?

**Comment by marouane53** [comment]
Try python 3.9

**Comment by odnar-dev** [comment]
looks like you need to import `wit_file_utils` from `tafrigh.utils.wit`
try my fork here : https://github.com/odnar-dev/transcribe

**Comment by marouane53** [comment]
The difference in behavior could be due to variations in the runtime
environment or Tafrigh library version. The added import statement in your
fork might have resolved an issue specific to your setup. If the original
code works without the import, it may not be necessary. Code behavior can
be influenced by factors like library versions and dependencies.

**Comment by odnar-dev** [comment]
i had the same problem, using python 3.11.8 and in a new environment

----

after doing some digging on how tafrigh work,  i found this

![image](https://github.com/marouane53/transcribe/assets/73726132/64cedf46-2228-480a-8e33-d941412d3535)

 by using some magic called debugging i found that they try to import two back-ends : WitRecognizer , WhisperRecognizer  
and if one failed to import they just skip it,
so when they try to import WitRecognizer, which fail because of a missing dependency `pydub` , they skip importing `wit_file_utils` 
and when your script call the client,  it throw the NameError, cause `wit_file_utils` which is not defined look alot like  `file_utils` 

- **so all you need to do to fix this is :  install  `pydub`**

this is a list of all the dependencies that are related to tafrigh and needed : `pydub, scipy, auditok, numpy, requests`

---
or just install tafrigh with : `pip install "tafrigh[wit]" ` which install tafrigh with all dependencies that are related to WitRecognizer

**Comment by yassinerebas** [comment]
Thank you, guys, it worked


> i had the same problem, using python 3.11.8 and in a new environment
> 
> after doing some digging on how tafrigh work, i found this
> 
> ![image](https://private-user-images.githubusercontent.com/73726132/317901857-64cedf46-2228-480a-8e33-d941412d3535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTE3NzksIm5iZiI6MTcxMTcxMTQ3OSwicGF0aCI6Ii83MzcyNjEzMi8zMTc5MDE4NTctNjRjZWRmNDYtMjIyOC00ODBhLThlMzMtZDk0MTQxMmQzNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExMjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxY2ZmNWRlMjNjNWI4NzQyYzY4ZDM0ZmRkZGQwMmZlYTg3MmQ0NzBiYTk0YjI5ZjA3NjkwNWEyYmE4OWFlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9CFbMrQz_8WIpBn7dnYgVcloYKTV47VPYxMFikWNZKY)
> 
> by using some magic called debugging i found that they try to import two back-ends : WitRecognizer , WhisperRecognizer and if one failed to import they just skip it, so when they try to import WitRecognizer, which fail because of a missing dependency `pydub` , they skip importing `wit_file_utils` and when your script call the client, it throw the NameError, cause `wit_file_utils` which is not defined look alot like `file_utils`
> 
> * **so all you need to do to fix this is :  install  `pydub`**
> 
> this is a list of all the dependencies that are related to tafrigh and needed : `pydub, scipy, auditok, numpy, requests`
> 
> or just install tafrigh with : `pip install "tafrigh[wit]" ` which install tafrigh with all dependencies that are related to WitRecognizer

**Comment by marouane53** [comment]
> i had the same problem, using python 3.11.8 and in a new environment
> 
> after doing some digging on how tafrigh work, i found this
> 
> ![image](https://private-user-images.githubusercontent.com/73726132/317901857-64cedf46-2228-480a-8e33-d941412d3535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MjMwMTQsIm5iZiI6MTcxMTcyMjcxNCwicGF0aCI6Ii83MzcyNjEzMi8zMTc5MDE4NTctNjRjZWRmNDYtMjIyOC00ODBhLThlMzMtZDk0MTQxMmQzNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE0MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNzhjNDNjMDUyMzJlODI2ZTZlMTYzODAwZWY1ZWNkODA1YmYxOTE0NjAxMTIxZWQyOGRlMzZiY2Q2M2NkNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsLQjyxQwUzrdgiRrJopeWjG1lhxV7YnGhNKddQEzQ4)
> 
> by using some magic called debugging i found that they try to import two back-ends : WitRecognizer , WhisperRecognizer and if one failed to import they just skip it, so when they try to import WitRecognizer, which fail because of a missing dependency `pydub` , they skip importing `wit_file_utils` and when your script call the client, it throw the NameError, cause `wit_file_utils` which is not defined look alot like `file_utils`
> 
> * **so all you need to do to fix this is :  install  `pydub`**
> 
> this is a list of all the dependencies that are related to tafrigh and needed : `pydub, scipy, auditok, numpy, requests`
> 
> or just install tafrigh with : `pip install "tafrigh[wit]" ` which install tafrigh with all dependencies that are related to WitRecognizer

Amazing work. Thank you

**Comment by BoOoOoOmmm** [comment]
if i want to use it in colab how i do, because i try it and doesn't work.

**Comment by BounharAbdelaziz** [comment]
pip install "tafrigh[wit]" worked for me, thanks @odnar-dev ;)

**Comment by AliOsm** [comment]
> if i want to use it in colab how i do, because i try it and doesn't work.

Tafrigh is already available on Colab: https://tafrigh.ieasybooks.com.

**Comment by AliOsm** [comment]
Tafrigh now is available through Docker with pre-built images, [check the docs](https://github.com/ieasybooks/tafrigh?tab=readme-ov-file#%D8%A7%D9%84%D8%AA%D9%81%D8%B1%D9%8A%D8%BA-%D8%A8%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-docker).
